version: "3.9"

services:
  web:
    build: .
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/mydb"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
   image: redis:7-alpine
   container_name: redis
   command: ["redis-server", "--requirepass", "myredispassword"]  # Set password
   ports:
    - "6380:6379"  # Map host port 6380 to container 6379 to avoid conflicts
   restart: always




volumes:
  postgres_data:
